# Generated by Django 4.2.4 on 2023-08-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("bookid", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=30)),
            ],
        ),
    ]
